Fix GallerySettingsCrash when attempting animation of a detached view
java.lang.IllegalStateException: Cannot start this animator on a detached view!
	at android.view.RenderNode.addAnimator(RenderNode.java:812)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:300)
	at android.view.RenderNodeAnimator.setTarget(RenderNodeAnimator.java:282)
	at android.animation.RevealAnimator.<init>(RevealAnimator.java:37)
	at android.view.ViewAnimationUtils.createCircularReveal(ViewAnimationUtils.java:55)
	at com.google.android.apps.muzei.gallery.GallerySettingsActivity$18$3.run(GallerySettingsActivity.java:896)

Caused by attempting to create a circular reveal on a detached view. Simple enough to not run the animation if the view is detached.