Work around EventBus use of reflection
Since MuzeiWallpaperService.Engine now has a method that uses WallpaperColors, EventBus crashes on older versions of Android where that doesn't exist due to its use of reflection going through all methods in the Subscriber. Moving the EventBus methods into its own inner class prevents the reflection from iterating over the WallpaperColors methods.

Exception java.lang.NoClassDefFoundError: android/app/WallpaperColors
java.lang.Class.getDeclaredMethods (Class.java)
java.lang.Class.getPublicMethodsRecursive (Class.java:894)
java.lang.Class.getMethods (Class.java:877)
org.greenrobot.eventbus.SubscriberMethodFinder.findUsingReflectionInSingleClass (SubscriberMethodFinder.java:157)
org.greenrobot.eventbus.SubscriberMethodFinder.findUsingInfo (SubscriberMethodFinder.java:88)
org.greenrobot.eventbus.SubscriberMethodFinder.findSubscriberMethods (SubscriberMethodFinder.java:64)
org.greenrobot.eventbus.EventBus.register (EventBus.java:136)
com.google.android.apps.muzei.MuzeiWallpaperService$MuzeiWallpaperEngine.onCreate (MuzeiWallpaperService.java:194)
android.service.wallpaper.WallpaperService$Engine.attach (WallpaperService.java:786)
android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1046)
com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:40)
android.os.Handler.dispatchMessage (Handler.java:102)