Fix Wearable crashes
Wearable 2.0.4 is bad and should feel bad.

Exception java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/wearable/watchface/IWatchFaceService$Stub;
android.support.wearable.watchface.WatchFaceService$Engine.onSetBinder (WatchFaceService.java:459)
android.support.wearable.watchface.WatchFaceService$Engine.onCommand (WatchFaceService.java:426)
android.service.wallpaper.WallpaperService$Engine.doCommand (WallpaperService.java:977)
android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1191)
com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:37)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5422)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)

Caused by java.lang.ClassNotFoundException: Didn't find class "android.support.wearable.watchface.IWatchFaceService$Stub" on path: DexPathList[[zip file "/system/framework/com.google.android.wearable.jar", zip file "/data/app/net.nurik.roman.muzei-1/base.apk"],nativeLibraryDirectories=[/data/app/net.nurik.roman.muzei-1/lib/arm, /vendor/lib, /system/lib]]
dalvik.system.BaseDexClassLoader.findClass (BaseDexClassLoader.java:56)
java.lang.ClassLoader.loadClass (ClassLoader.java:511)
java.lang.ClassLoader.loadClass (ClassLoader.java:469)
android.support.wearable.watchface.WatchFaceService$Engine.onSetBinder (WatchFaceService.java:459)
android.support.wearable.watchface.WatchFaceService$Engine.onCommand (WatchFaceService.java:426)
android.service.wallpaper.WallpaperService$Engine.doCommand (WallpaperService.java:977)
android.service.wallpaper.WallpaperService$IWallpaperEngineWrapper.executeMessage (WallpaperService.java:1191)
com.android.internal.os.HandlerCaller$MyHandler.handleMessage (HandlerCaller.java:37)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:148)
android.app.ActivityThread.main (ActivityThread.java:5422)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:726)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:616)