Pre-scale widget images to avoid exceeding the maximum bitmap memory usage
java.lang.RuntimeException: An error occurred while executing doInBackground()
 at android.os.AsyncTask$3.done(AsyncTask.java:325)
Caused by: java.lang.IllegalArgumentException: RemoteViews for widget update exceeds maximum bitmap memory usage (used: 16384000, max: 12441600)
  at android.os.Parcel.readException(Parcel.java:1688)
  at android.os.Parcel.readException(Parcel.java:1637)
  at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:647)
  at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:474)
  at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:547)
  at com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground(AppWidgetUpdateTask.java:142)
  at com.google.android.apps.muzei.widget.AppWidgetUpdateTask.doInBackground(AppWidgetUpdateTask.java:52)