Fix crash on null is_tree_uri columns in Gallery
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:353)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: chosen_photos2.is_tree_uri (code 1299)
	at android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
	at android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:734)
	at android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754)
	at android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64)
	at android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1679)
	at android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1608)
	at android.arch.persistence.db.framework.FrameworkSQLiteDatabase.execSQL(FrameworkSQLiteDatabase.java:240)
	at com.google.android.apps.muzei.gallery.GalleryDatabase$4.migrate(GalleryDatabase.java:159)
	at android.arch.persistence.room.RoomOpenHelper.onUpgrade(RoomOpenHelper.java:73)
	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.onUpgrade(FrameworkSQLiteOpenHelper.java:118)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:299)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:194)
	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper$OpenHelper.getWritableSupportDatabase(FrameworkSQLiteOpenHelper.java:93)
	at android.arch.persistence.db.framework.FrameworkSQLiteOpenHelper.getWritableDatabase(FrameworkSQLiteOpenHelper.java:54)
	at android.arch.persistence.room.RoomDatabase.query(RoomDatabase.java:193)
	at com.google.android.apps.muzei.gallery.ChosenPhotoDao_Impl.getChosenPhotoBlocking(ChosenPhotoDao_Impl.java:168)
	at com.google.android.apps.muzei.gallery.GalleryProvider.openFile(GalleryProvider.java:77)
	at android.content.ContentProvider.openAssetFile(ContentProvider.java:1545)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1725)
	at android.content.ContentProvider.openTypedAssetFile(ContentProvider.java:1791)
	at android.content.ContentProvider$Transport.openTypedAssetFile(ContentProvider.java:425)
	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1410)
	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:1247)
	at android.content.ContentResolver.openInputStream(ContentResolver.java:967)
	at com.google.android.apps.muzei.sync.DownloadArtworkTask.openUri(DownloadArtworkTask.java:119)
	at com.google.android.apps.muzei.sync.DownloadArtworkTask.doInBackground(DownloadArtworkTask.java:74)
	at com.google.android.apps.muzei.sync.DownloadArtworkTask.doInBackground(DownloadArtworkTask.java:47)
	at android.os.AsyncTask$2.call(AsyncTask.java:333)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	... 4 more